version: '3'
services: 
    guppy:
        build: .
        image: 
        restart: always
        ports:
            - 80:80
        environment:
            - GIN_MODE=release
            - SERVER_ADDRESS=0.0.0.0
            - SERVER_PORT=80
            - SERVER_TIMEZONE=Asia/Jakarta
            - SWAGGER_SERVER_ADDRESS=http://0.0.0.0
        command: ./main -e production  